#define PROGRAM_NAME "bnk-extract GUI"

// random numbers or smth idk
#define OPTIONSDIALOG_RESOURCE 141

#define IDR_MYMENU 101
#define IDI_MYICON 201

#define IDM_SETTINGS 301

#define ID_AUTOPLAY_AUDIO 401
#define ID_EXTRACT_AS_WEM 402
#define ID_EXTRACT_AS_OGG 403
#define ID_MULTISELECT_ENABLED 404

#define IDR_KEYCOMBINATIONS 501
#define IDM_COPY 502
